### ISSUE TITLE
Some vars are undefined

### ISSUE THREAD

**Issue by ramasilveyra** [auth0/styleguide#95]
Some stylus vars are undefined and are emitted to the latest css bundle (https://cdn.auth0.com/styleguide/4.8.8/index.css):

``` css
.img-thumbnail {
  padding: $thumbnail-padding;
  line-height: 2;
  background-color: $thumbnail-bg;
  border: 1px solid $thumbnail-border;
  border-radius: $thumbnail-border-radius;
  transition: all 0.2s ease-in-out;
  display: inline-block;
  max-width: 100%;
  height: auto;
}
```

``` css
pre code {
  padding: 0;
  font-size: inherit;
  color: inherit;
  white-space: pre-wrap;
  background-color: transparent;
  border-radius: $border-radius;
}
```

``` css
.hue-palette {
  border-radius: $border-radius;
  color: #fff;
  font-size: 13px;
  line-height: 40px;
  list-style: none;
  margin: 0 0 40px 0;
  padding: 0;
  overflow: hidden;
  text-transform: uppercase;
}
```

Also I found this:

``` css
table {
  td: ,;
}
```

Maybe we can add a linter just to find css **parsing errors** to avoid this issues in the future to run on `npm test` and on `npm poststart` only on the final css bundle (very good linter: [stylelint](https://github.com/stylelint/stylelint)).
